# Generated by Django 5.1 on 2024-08-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soildata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec', models.IntegerField()),
                ('ph', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
            ],
        ),
    ]
